### ISSUE TITLE
R5: Backend: Get data from openFDA

### ISSUE THREAD

**Issue by OrbisOpenSource** [OrbisTechnologies/Orbis180#1]
Implement web service to get data from openFDA API

**Comment by amazingDeveloper** [comment]
[Implemented]
Created a REST service class that query openFDA database and pull the data from their database.

[Testing Finished]
The screenshot of the data pull from the openFDA database is attached to this ticket.

![openfdadatapull](https://cloud.githubusercontent.com/assets/12970944/8269832/d7fb481a-178a-11e5-8232-f5adae4d2d60.png)

**Comment by ezakour** [comment]
Completed.
SQA
