### ISSUE TITLE
R8: Web Application: Browser Reqs: The software shall be displayed uniformly from either a mobile device, laptop or desktop

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#10]

**Comment by cb4000** [comment]
Due to the placement of the navbar on the left, this may not be possible (may need responsive design) on smaller displays. We may need to revisit this.

**Comment by kojolinder** [comment]
Visually inspected on laptop.   Unable to verify on desktop and mobile.  Ran out of time.

**Comment by ezakour** [comment]
Completed.
SQA
