### ISSUE TITLE
CR6: Search Window: Create baseball cards of search results with scroll down bar

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#100]
Add the line

**Comment by apeenan** [comment]
Baseball card result structure made by @cnithianandam and implemented in a scroll bar to adhere to requirements and house large number of results in a fixed container. Search results page starts off blank and results appear in their own baseball cards when the search is submitted with "Submit Search" button. This feature was implemented using JQuery and HTML for the baseball card structure, and JQuery to dynamically generate the baseball cards when a search is performed.
