### ISSUE TITLE
R84: Database: Ingest openFDA data into database

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#107]
Tools: Sesame

**Comment by amazingDeveloper** [comment]
Implemented methods call to pull data from openFDA Database and ingest those data into sesame.

![dataingestion](https://cloud.githubusercontent.com/assets/12970944/8339081/05ebc9ac-1a83-11e5-8505-067f8c4faed8.jpg)

**Comment by ezakour** [comment]
Completed.
SQA
