### ISSUE TITLE
CR18: Home Page: Add descriptions to the donut graphs using hover

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#118]
Classication type: 
Class I = Dangerous or defective products that predictably could cause serious health problems or death. 
Class II = Products that might cause a temporary health problem, or pose only a slight threat of a serious nature. 
Class III = Products that are unlikely to cause any adverse health reaction

Status Type
On-Going = A recall which is currently in progress.
Completed = The company in violation has retrieved all outstanding products or has completed all product corrections.
Terminated = FDA has determined that all reasonable efforts have been made to remove or correct the violation product 
Pending = Actions that have been determined to be recalls, but remain in the process of being classified.

Tools: JQuery

**Comment by apeenan** [comment]
Implemented as a footer on the overview page using HTML
