### ISSUE TITLE
DR5: Search: Remove 'Food Description' as header for baseball cards

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#121]
Tools: JQuery

**Comment by apeenan** [comment]
What will be the header for Baseball cards? Currently the header is set as the Product Description, however product descriptions may be too long so was thinking maybe recall number also i.e. "F-1415-2013"

**Comment by apeenan** [comment]
We will use the Recall Number as the title for each baseball card
