### ISSUE TITLE
CR30: Search Window: Modify search selection options

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#131]
Search button
'Search start date (yyyymmdd) (Req)'
'Search end date (yyyymmdd) (Req)'
'Location (XX) (Req)'

'Advanced Search'
'Keyword (one field)'
'Food Group (one field)'

Tools: JQuery

**Comment by apeenan** [comment]
Updated using bootstrap datepicker for the start date and end date and food group drop down
