### ISSUE TITLE
R13: Home Page: The software Home Page shall include the Wiley logo

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#15]

**Comment by kojolinder** [comment]
![logo](https://cloud.githubusercontent.com/assets/9564269/8307871/249fe40e-198f-11e5-98b8-0bbbdb19de0d.gif)

**Comment by apeenan** [comment]
Logo added and resized with Bootstrap and HTML to the navigation sidebar of the Homepage and other subsequent pages

**Comment by ezakour** [comment]
Completed.
SQA
