### ISSUE TITLE
DR19: Monitor Window: Verify that all queries are being searched and stored

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#172]

**Comment by cb4000** [comment]
Fixed an issue wherein any issues processing query results caused said query to not be monitored.

**Comment by cb4000** [comment]
There were several issues with monitoring, the most important of which is that the query results were being monitored after being processed. Any issue with processing led to queries not being monitored (fixed in e752ed2afd07ce8c0fa0e41c75a9524fa26e9128).
