### ISSUE TITLE
DR21: Search Window: Add indicator to suggest that search process is moving

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#174]

**Comment by amazingDeveloper** [comment]
Added processing indicator...when user clicked on the Submit Search button, the submit button deactivates and display processing text...screenshots are below:

![processing_1](https://cloud.githubusercontent.com/assets/12970944/8546165/619a0f34-2483-11e5-9463-07e9c08df896.jpg)
![processing_2](https://cloud.githubusercontent.com/assets/12970944/8546164/6198216a-2483-11e5-9c0d-5713d289af2c.jpg)
![processing_3](https://cloud.githubusercontent.com/assets/12970944/8546166/619a3770-2483-11e5-9c91-3a6d1325a384.jpg)
