### ISSUE TITLE
CR43: Search Window: Upload and link Release notes, Install Guide and Help File on Search, Overview and Monitor Windows

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#177]

**Comment by amazingDeveloper** [comment]
Linked Release Notes, Install Guide & Help File on the Search, overview &  Monitor Windows.

![download docs](https://cloud.githubusercontent.com/assets/12970944/8547926/fbefed72-248f-11e5-9fb4-602810238474.jpg)
