### ISSUE TITLE
R17: Home Page: The Software Home Page banner shall display total US recalls since 2004 along with the caption 'Total US Recalls since 1/1/2004'

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#19]
Derived from FDA metadata: Tools: JQuery

**Comment by kojolinder** [comment]
metadata: report_date, country

**Comment by apeenan** [comment]
Jquery ajax request used to get total US recalls from openFDA and d3 used to visualize the data in banner

**Comment by ezakour** [comment]
Completed.
SQA
