### ISSUE TITLE
R6: Backend - Create ontology model to be used as the schema for ingestion into Sesame for the Food API

### ISSUE THREAD

**Issue by candino01** [OrbisTechnologies/Orbis180#2]
Assess the contents of the response from openFDA APIs and generate an ontology model to represent the data into RDF.

**Comment by candino01** [comment]
Initial openFDA ontology model was merged into master.

**Comment by kojolinder** [comment]
Requirement ticket
R84: Database: Ingest openFDA data into database #107

**Comment by ezakour** [comment]
Completed.
SQA
