### ISSUE TITLE
R18: Home Page: The Software Home Page banner shall display total year-to-date recalls  along with the caption 'Total year-to-date Recalls'

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#20]
derived from FDA metadata: Tools: JQuery

**Comment by kojolinder** [comment]
metadata: recall_initiation_date,status, completed,pending

**Comment by apeenan** [comment]
Top banner includes year to date recalls and the 'Total year to date Recalls' caption.Jquery  Ajax request used to get count from OpenFDA and display on banner

**Comment by ezakour** [comment]
Completed.
SQA
