### ISSUE TITLE
R19: Home Page: The Software Home Page banner shall display average recalls per day over year-to-date along with the caption 'Average Recalls per day over calendar year'

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#21]
Derived from FDA metadata. Tools: JQuery

**Comment by kojolinder** [comment]
metadata:  recall_initiation_date,status, completed,pending, on-going, country

**Comment by apeenan** [comment]
Jquery ajax request to openFDA, visualized in d3 used to satisfy this requirement

**Comment by ezakour** [comment]
Completed.
SQA
