### ISSUE TITLE
R20: Home Page: The Software Home Page banner shall display % yearly change in total recalls by calendar year along with the caption '% Recall change by calendar year'

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#22]
Derived from FDA metadata.  Tools: JQuery

**Comment by kojolinder** [comment]
metadata:  recall_initiation_date,status, completed,pending, on-going, country

**Comment by apeenan** [comment]
Requirement satisfied with jquery to make an ajax call to openFda to get the data, javascript used to conduct the calculation and d3 used for the visualization of the banner

**Comment by ezakour** [comment]
Completed.
SQA
