### ISSUE TITLE
R1: Backend: Setup Environment

### ISSUE THREAD

**Issue by amazingDeveloper** [OrbisTechnologies/Orbis180#3]
Setup your dev environment by installing Tomcat, Sesame & Jersey webservice

**Comment by amazingDeveloper** [comment]
[Environment Setup Finished]
Setup Centos VM and installed Tomcat, Sesame and Jersey webservice library.

[Testing Finished]
Ran Tomcat, Sesame & Jersey Webservice instances. The screenshots are attached to this ticket for reference.


![apache tomcat](https://cloud.githubusercontent.com/assets/12970944/8269070/5b11d58a-1767-11e5-8dc9-d7c29028e745.png)
![jersey webservice](https://cloud.githubusercontent.com/assets/12970944/8269068/5b116f5a-1767-11e5-9d7d-cb148f79fe32.png)
![openrdf sesame](https://cloud.githubusercontent.com/assets/12970944/8269071/5b13cdcc-1767-11e5-9b69-92f0e22a46d3.png)
![openrdf workbench](https://cloud.githubusercontent.com/assets/12970944/8269069/5b119980-1767-11e5-9f9c-71cc984934d0.png)

**Comment by ezakour** [comment]
Complete.
