### ISSUE TITLE
R28: Home Page: The Software Home Page bar graph shall allow the user to mouse over the bar to display numeric values

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#31]
Tools: JQuery
metadata: recdall_initiation_date, initial_firm_notification

**Comment by apeenan** [comment]
c3 used to satisfy this requirement. Horizontal bar chart built with hover over implementation to see the numeric values

**Comment by ezakour** [comment]
Completed.
SQA
