### ISSUE TITLE
R29: Home Page: The Software Home Page line graph shall display a timeline graph of recalls over time

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#32]
Tools: JQuery
metadata: recall_initiation_date, voluntary_mandated

**Comment by apeenan** [comment]
c3 timeseries graph used to satisfy this requirement. jquery is utilized to make ajax request to openfda endpoint to get the dates as well as the number of recalls on that particular date

**Comment by ezakour** [comment]
Completed.
SQA
