### ISSUE TITLE
R30: Home Page: The Software Home Page line graph shall provide a scrolling highlight line that displays line graph numeric values

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#33]
Tools: JQuery
metadata:voluntary_mandated, recall_initiation_date

**Comment by apeenan** [comment]
this is implemented with c3. when you hover over a point on the line graph, it displays the date as well as the number of recalls for that particular day. A subgraph is added as well to zoom in on particular regions of the overall graph.

**Comment by ezakour** [comment]
Completed.
SQA
