### ISSUE TITLE
R31: Home Page: The Software Home Page line graph shall contain a selection object to allow users to choose among several fixed time intervals

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#34]
Tools: JQuery
metadata:recall_initiation_date

**Comment by apeenan** [comment]
Overview homepage has a subgraph that the user can click into to zoom into specific portions of the overall graph. c3 used to satisfy this requirement.

**Comment by ezakour** [comment]
Completed.
SQA
