### ISSUE TITLE
R34: Search Window: Search window shall display results based on user selected filters (city, state, initiation date range)

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#38]
Tools: JQuery
metadata: city, state, recall_initiation_date, product_description

**Comment by apeenan** [comment]
Implemented with beginning date range to end date range and location by state (required fields) and optionally the ability to search using keyword and selection of food group. HTML used to satisfy this requirement, JQuery used to send these parameter fields to the endpoint that will give back the results.

**Comment by ezakour** [comment]
Completed.
SQA
