### ISSUE TITLE
R7: Backend: Parse and store results from OpenFDA's API into Sesame

### ISSUE THREAD

**Issue by candino01** [OrbisTechnologies/Orbis180#4]
Create the storage framework to parse and store the openFDA Food API results into RDF in Sesame.

**Comment by candino01** [comment]
Including sample graph from three documents loaded into sesame.

![sampleopenfdadatafromontology](https://cloud.githubusercontent.com/assets/6783516/8289953/a35aa894-18ed-11e5-97ad-edb8b7bf5701.png)

**Comment by kojolinder** [comment]
Reference requirement ticket

R84: Database: Ingest openFDA data into database #107

**Comment by ezakour** [comment]
Completed.
SQA
