### ISSUE TITLE
R40: Search Window: Search window shall display all query results in chronological order and include all metadata

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#44]
Tools: D3
metadata: 
    reason_for_recall
    "status"
    "distribution_pattern
    "product_quantity
    "recall_initiation_date"
    "state
    "event_id"
    "product_type
    "product_description"
    "country"
    "city
    "recalling_firm
    "report_date
    "voluntary_mandated
    "classification
    "code_info
    "initial_firm_notification":

**Comment by cb4000** [comment]
Tools: Update, this component no longer requires d3.

**Comment by kojolinder** [comment]
Visually inspected. completed.

**Comment by ezakour** [comment]
Completed.
SQA
