### ISSUE TITLE
R50: Data Services:  Ingest: Ingest OpenFDA data into Sesame

### ISSUE THREAD

**Issue by amazingDeveloper** [OrbisTechnologies/Orbis180#54]
Create methods to ingest openFDA data into sesame

**Comment by kojolinder** [comment]
Tools: Sesame: Jersey

**Comment by amazingDeveloper** [comment]
Implemented methods call to pull data from openFDA Database and ingest those data into sesame.

![dataingestion](https://cloud.githubusercontent.com/assets/12970944/8337648/66a642f8-1a7a-11e5-9f03-26127af3c1dc.jpg)

**Comment by ezakour** [comment]
Completed.
SQA
