### ISSUE TITLE
R57: Data Services: Analytics: Overview services shall calculate the total US recalls

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#61]
Tools: D3
metadata: country, recall_initiation_date, recall_description

**Comment by cb4000** [comment]
Update: Tools: D3 + C3

**Comment by cb4000** [comment]
This is being populated by data from OpenFDA's Rest endpoint.

**Comment by ezakour** [comment]
Completed.
SQA
