### ISSUE TITLE
R63: Data Services: Analytics: Overview services shall calculate the % of food recalls by recall status

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#67]
Tools: JQuery
metadata: status, recall_initiation_date

**Comment by apeenan** [comment]
jquery ajax request to openfda used to get the total number of food recalls for each category of recall status: ongoing, completed, terminated. This information is used for a donut pie chart on the overview page

**Comment by ezakour** [comment]
Completed.
SQA
