### ISSUE TITLE
R65: Data Services: Analytics: Overview services shall calculate the number of food recalls over time

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#69]
Tools: JQuery
metadata: recall_initiation_data

**Comment by apeenan** [comment]
jquery ajax request used to gt the number of food recalls occurring per reported date queried from openfda end point. this data is used to build the timeseries chart on the overview page.

**Comment by ezakour** [comment]
Completed.
SQA
