### ISSUE TITLE
R70: Data Services: Monitoring: Monitoring services shall calculate the total number queries

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#75]
Tools: MySQL

**Comment by cb4000** [comment]
Apache Derby is the SQL tool used for now, as it doesn't require a server install, and we only need rudimentary, single-class, SQL functionality

**Comment by cb4000** [comment]
Implemented and integrated in front end.

**Comment by ezakour** [comment]
Completed.
SQA
