### ISSUE TITLE
R71: Data Services: Monitoring: Monitoring services shall calculate query time (ms)

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#76]
Tools: MySQL

**Comment by cb4000** [comment]
We have to figure out how to calculate the request delay on the front end. Apache Derby is the SQL tool used for now, as it doesn't require a server install, and we only need rudimentary, single-class, SQL functionality.

**Comment by cb4000** [comment]
The delay is being is is being calculated by javascript on the front-end, and stored in the monitoring service.

**Comment by ezakour** [comment]
Completed.
SQA
