### ISSUE TITLE
R72: Data Services: Monitoring: Monitoring services shall calculate total year-to-date queries

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#77]
Tools: MySQL

**Comment by cb4000** [comment]
Apache Derby is the SQL tool used for now, as it doesn't require a server install, and we only need rudimentary, single-class, SQL functionality

**Comment by cb4000** [comment]
Reachable @ /rest/monitor/summary  on the REST endpoint.

**Comment by ezakour** [comment]
Completed.
SQA
