### ISSUE TITLE
R73: Data Services: Monitoring: Monitoring services shall calculate average queries per day

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#78]
Tools: MySQL

**Comment by cb4000** [comment]
Apache Derby is the SQL tool used for now, as it doesn't require a server install, and we only need rudimentary, single-class, SQL functionality

**Comment by cb4000** [comment]
Implemented as part of the of rest/monitor/summary REST endpoint.

**Comment by ezakour** [comment]
Completed.
SQA
