### ISSUE TITLE
R74: Data Services: Monitoring: Monitoring services shall calculate yearly change in total queries

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#79]
Tools: MySQL

**Comment by cb4000** [comment]
Apache Derby is the SQL tool used for now, as it doesn't require a server install, and we only need rudimentary, single-class, SQL functionality

**Comment by kojolinder** [comment]
Removed.  Not enough data points.

**Comment by ezakour** [comment]
Completed.
SQA
