### ISSUE TITLE
Create Charts for Overview Page

### ISSUE THREAD

**Issue by apeenan** [OrbisTechnologies/Orbis180#8]
Pie charts need to be created for
-class type (I,II,III)
-product type (food,drug,device)
-recall status (completed, pending, terminated, ongoing)

Horizontal Barchart
-Notification types

Timeline Chart

**Comment by cb4000** [comment]
Charts integration completed and added to skeleton files. C3 and D3 integrated via CDN.

**Comment by kojolinder** [comment]
Requirement tickets:

R30: Home Page: The Software Home Page line graph shall provide a scrolling highlight line that displays line graph numeric values #33
R26: Homepage: The Software Home Page donut graph shall display recalls by recall status #28 
R25: Homepage: The Software Home Page donut graph shall display recalls by classification #27 
R27: Home Page: The Software Home Page donut graph shall allow the user to mouse over the bar to display numeric values #29
