### ISSUE TITLE
R75: Data Services: Monitoring: Monitoring services shall calculate the total number of query counts over time

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#80]

**Comment by kojolinder** [comment]
Tools: MySQL

**Comment by cb4000** [comment]
Apache Derby is the SQL tool used for now, as it doesn't require a server install, and we only need rudimentary, single-class, SQL functionality

**Comment by cb4000** [comment]
Added the endpoint monitor/querytimes to provide this.
