### ISSUE TITLE
R76: Data Services: Monitoring: Monitoring services shall calculate the total number of queries by type

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#81]

**Comment by kojolinder** [comment]
Tools: MySQL

**Comment by cb4000** [comment]
Apache Derby is the SQL tool used for now, as it doesn't require a server install, and we only need rudimentary, single-class, SQL functionality

**Comment by cb4000** [comment]
This is a deprecated requirement from an earlier design.

**Comment by ezakour** [comment]
Completed.
SQA
