### ISSUE TITLE
R77: Data Services: Monitoring: Monitoring services shall calculate the top five queries to date

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#82]

**Comment by kojolinder** [comment]
Tools: MySQL

**Comment by cb4000** [comment]
Apache Derby is the SQL tool used for now, as it doesn't require a server install, and we only need rudimentary, single-class, SQL functionality

**Comment by cb4000** [comment]
Currently top 5 is the top 5 keywords used and their counts.

**Comment by ezakour** [comment]
Completed.
SQA
