### ISSUE TITLE
R78: Data Services: Monitoring: Monitoring services shall extract the total number of queries

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#83]

**Comment by kojolinder** [comment]
Tools: MySQL

**Comment by cb4000** [comment]
Apache Derby is the SQL tool used for now, as it doesn't require a server install, and we only need rudimentary, single-class, SQL functionality

**Comment by cb4000** [comment]
Functionality has been pushed to the integration branch, is not fully integrated with front end,

**Comment by ezakour** [comment]
Completed.
SQA
