### ISSUE TITLE
R80: Data Services: Monitoring: The default view of the search results will be blank

### ISSUE THREAD

**Issue by kojolinder** [OrbisTechnologies/Orbis180#85]
Tools: JQuery

**Comment by apeenan** [comment]
Implemented in branch CR28_SearchResults. When the user initially enters the search page, the area where the search results would generate is initially empty. When the user makes selections for search, upon hitting the search button text with 'Number of Results' appears and each individual baseball card for each result appears in a scrollable bar. The user may then select different parameters and run the search again and the results will reinitialize.

This dynamic generation of the results uses JQuery and HTML.

**Comment by ezakour** [comment]
Completed.
SQA
